default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  user: postgres
  password: password
  database: book_app_development

test:
  <<: *default
  host: db
  user: postgres
  password: password
  database: book_app_test

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '') %>
